### PR TITLE
Added configuration regarding usage of AdapterId mechanism

### LINKED ISSUE #213: IES_Adapter: missing configuration regarding usage of `AdapterId` mechanism
#### Description:

IES uses the CRUD mechanism. The CRUD mechanism leverages the `AdapterId` feature if so requested by the `AdapterSettings` (defaults to `true`). However, no `IESAdapterId` is defined in the project (apart from some `SurfaceIndexFragment` that however does not implement the `IAdapterId` interface). @IsakNaslundBh 

This is the most likely explanation of some push failures highlighted by @jamesramsden-bh and others:
image

#### Steps to reproduce:

As in @jamesramsden-bh script.

#### Expected behaviour/needed action:

Push should not fail, `AdapterSettings.UseAdapterId` must be set to `false` in the IES ctor.

image

#### Test file(s):

Ask @jamesramsden-bh and others with this failure.

### PR DESCRIPTION
**Pull request by CKBoulter**
Set adapterID to false to address issue #213
Closes #213 

Due to recent changes in how the adapters work, an error is now thrown if the adapterID is neither implemented or set to false.

### CODE REVIEW

**Review by jamesramsden-bh — APPROVED** [review]
Tested against IES Toolkit, push now no longer throws an error

**Review by jamesramsden-bh — APPROVED** [review]
In addition to previous review, the punctuation has now been improved in the attributes.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Code changes are in line with expectations from the issue. Documentation has been improved with grammatically correct endings. Great work @CKBoulter 👍

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
