### PR TITLE
Refactor to use ActionConfig instead of Settings

### LINKED ISSUE #220: Handle push of multiple object types
#### Description:

Edge case discovered during the 6.1 Beta testing but as a 'feature' request it is not expected to be handled until the 6.2 milestone.

Currently IES Toolkit Push can only handle a list of Panel objects but should be adapted to ignore objects that aren't applicable.

For example, if you Pull a GEM file using the IES adapter it creates both BHoM Panels (with Openings if applicable) and Space objects. If you then try to Push this same list of objects (including both Panels & Spaces) then it results in an empty GEM file because the Push is triggered twice; once by the Panel objects (which works correctly) then again by the Space objects (which fails quietly and overwrites the successful Panel push).

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #220

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check compliance
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check compliance
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by michaelhoehn — APPROVED** [review]
Demo from @FraserGreenroyd worked okay, approving to unblock @Tom-Kingstone for further work.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
