### PR TITLE
Filter to pull all elements by default, filter to Panels or Space on request

### LINKED ISSUE #147: Ability to filter for panels on pull
Currently the default pull is to pull panels and not spaces.

Change this so default pull is panels and spaces, and a filter request on panel type is needed to get just panels.

As discussed with @rboulton-BH

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #147 

 ### Test files

 ### Changelog

 ### Additional comments
Filter to pull on no request, you should get Panels and Spaces.
Add FilterRequest type to Panel and you should get only panels.
Change FilterRequest type to Space and you should get only spaces.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Pull request merged**
