### PR TITLE
Fixing shades for 3D building use

### LINKED ISSUE #200: Resolve IES Shades not importing as 3D objects
#### Description:

Currently when shades are exported to IES they are exported as individual surfaces. IES natively can't produce this, and some tests have shown that IES doesn't correctly simulate 2D shades. See images from Mostapha here: https://discourse.pollination.cloud/t/revit-to-rhino-to-gem-to-ies-ve-adding-thickness-to-shading-elements/2021/2

#### Steps to reproduce:

Export panels as Shade type to GEM and import into IES

#### Expected behaviour:

Closed polysurfaces in Rhino, or Shade type Panels sharing the same name in Grasshopper should be imported into IES as singular combined geometry, not individual surfaces

#### Test file(s):

None to hand

### PR DESCRIPTION
**Pull request by kprusicka**
### Issues addressed by this PR

 Closes #200

### CODE REVIEW

**Comment by kprusicka** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Code changes make sense, approving for merge to deploy via alpha for further testing.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
