### PR TITLE
Fixing shade push

### LINKED ISSUE #202: Shade spaces not registered as the correct type in IES
#### Description:
Following the merging of #201 which improves the pushing of 3D shades to IES, there is an issue reported by the users that the type is not being correctly assigned causing IES to not detect them as shades but as additional rooms/spaces.

#### Steps to reproduce:
Push a model to GEM with 3D shades and import into IES - shade type is not correctly assigned.

#### Expected behaviour:
Shade type is correctly assigned.

In the file `IES_Engine/Convert/Environment/Space.cs`, lines 62/63, update to read something like this:

```
if(panels.First().IsShade())
{
    gemSpace.Add("TYPE\n");
    gemSpace.Add("4\n");
    gemSpace.Add("SUBTYPE\n");
    gemSpace.Add("0\n");
}
else
{
    gemSpace.Add("TYPE\n");
    gemSpace.Add("1\n");
    gemSpace.Add("SUBTYPE\n");
    gemSpace.Add("2001\n");
}
```

### PR DESCRIPTION
**Pull request by kprusicka**
### Issues addressed by this PR

 Closes #202

### CODE REVIEW

**Comment by kprusicka** [comment]
@BHoMBot Check required

**Comment by kprusicka** [comment]
@BHoMBot Thank you

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Code changes address the issue, tested through with @kprusicka and null handling added suitably.
Merging for deployment via alphas.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
