### PR TITLE
Fixed punctuation

### LINKED ISSUE #187: IES_Toolkit: Correct punctuation in Panel.cs
#### Broken rules:
IES_Engine/Convert/Environment/Panel.cs Line 90 currently reads
`[Input("iesSpace", "The IES representation of a space")]`

#### Suggestions to restore compliance:
Correct version is 
`[Input("iesPanel", "The IES representation of a space.")]`

### PR DESCRIPTION
**Pull request by robinflyman**
Closes #187 

Fixed punctuation in the relevant file.

### CODE REVIEW

**Review by jamesramsden-bh — APPROVED** [review]
Simple change, reviewed by inspection, LGTM

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check core

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check installer

**Comment by jamesramsden-bh** [comment]
@BHoMBot check copyright-compliance

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@jamesramsden-bh - feel this sums up this PR looking at the comments 🤣 
image

**Pull request merged**
