### PR TITLE
Opening fix

### LINKED ISSUE #177: Holes in floors/ceiling being reflected incorrectly on push
Hi Lina, Fraser, 

I've spotted a couple of things on my model with the IES toolkit that I'm hoping I can rope your help with - this is the first...

On the model I pulled from an existing IES GEM file to update glazing and then pushed back to GEM. 

I noticed that the holes in the ceiling/floor were not behaving as expected. 

Pulled model
image

Pushed model
image

The light blue shows the location of the hole, as you can see it's been flipped causing the Push version to be incorrect.

I've attached the GEM file from the pull and the push, and related files.

### PR DESCRIPTION
**Pull request by kprusicka**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #177

 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by kprusicka** [comment]
@BHoMBot Check versioning

**Comment by kprusicka** [comment]
@BHoMBot Check compliance

**Comment by kprusicka** [comment]
@BHoMBot Check versioning

**Comment by kprusicka** [comment]
@BHoMBot Check core
@BHoMBot Check serialisation
@BHoMBot  Check null-handling

**Review by FraserGreenroyd — APPROVED** [review]
Approving based on review and testing with @kprusicka and @IsakNaslundBh . Approving for release to alpha

**Comment by kprusicka** [comment]
@BHoMBot Check ready-to-merge

**Comment by kprusicka** [comment]
Dziekuje @BHoMBot

**Pull request merged**
