### PR TITLE
Fix ghost spaces being added to push export

### LINKED ISSUE #212: IES Push adding in 'ghost' spaces
#### Description:

The IES adapter Push is writing an additional `IES 0 0` into each space definition in the GEM file which is creating 'ghost' spaces when imported into IES. See snapshots as an example.
image
image

Having tested multiple Alpha installers from the past couple of months it looks as though the issue has crept in from #208. 
image

#### Steps to reproduce:

Push valid BHoM PanelsAsSpaces to GEM using IES adapter

#### Expected behaviour:

Removal of the additional `IES 0 0` within the space definition in the GEM file to remove the 'ghost' spaces occurring upon import.

#### Test file(s):

Use standard IES_TK Push procedure: https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/IES_Toolkit/IES_Toolkit_PushModel.gh?csf=1&web=1&e=maUOUM

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #212 

👻 👻 

image

### CODE REVIEW

**Review by kprusicka — DISMISSED** [review]
No more ghost spaces

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by rboulton-BH — APPROVED** [review]
Tested using the [standard IES test procedure.](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/IES_Toolkit?csf=1&web=1&e=89VTdN)

The GEM pushed no longer includes the `IES 0 0` and the 'ghost' spaces are not created when imported into IES so the fix works as expected. All other IES_TK functionality remains correct and unchanged.

The Pull still gives the error message already identified by @CKBoulter & @tobyoross in PR #211 but it does not appear to affect functionality.

Approval forthwith

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
