### PR TITLE
Functional tests for pulling panels and spaces

### LINKED ISSUE #231: NUnit test for pulling data from GEM files
#### Definition of the test :

In order to reduce regression of functionality that may be caused by future updates to the adapter, a functional unit test for pulling data from GEM files should be created. 

Similar to the pull tests in the robot toolkit, a set of tests shall be created that tests:
- Pulling objects of type: Space
- Pulling objects of type: Panel

A test model will be used that has a known number of spaces and panels, and the test will assert whether the number of objects pulled from the model using the IESAdapter is correct.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #231 

 
Functional tests for the the pull functionality have been created that test a number of scenarios:
- Pulling Panels from a model with 3D shades with openings
- Ditto without openings
- Pulling panels from a model with 2D shades with openings
- Ditto without openings
- Pulling spaces from a model with 3D shades
- Pulling spaces from a model with 2D shades
- Pulling the full model with 3D shades
- Pulling the full model with 2D shades

 ### Test files

 ### Changelog

 ### Additional comments

There are JSON files with the models that contain the serialised BHoM objects used to create the GEM files.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check project-compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check copyright-compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check unit-tests

**Review by FraserGreenroyd — APPROVED** [review]
Code reviewed and tests checked, happy to merge in.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
